name: property-front

services:
  front:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    expose: ["80"]
    networks: [platform]

networks:
  platform:
    name: platform
    external: true
